services:
  # ID Bot for getting Telegram user IDs
  id-bot:
    build: .
    container_name: remnawave-id-bot
    command: python get_telegram_id.py
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    env_file:
      - .env
    restart: unless-stopped
    profiles:
      - id-bot

  # Main Remnawave Admin Bot with debug logging
  remnawave-bot-debug:
    build: .
    container_name: remnawave-admin-bot-debug
    command: python main.py
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - REMNAWAVE_API_TOKEN=${REMNAWAVE_API_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
      - LOG_LEVEL=DEBUG
    env_file:
      - .env
    restart: unless-stopped
    profiles:
      - debug

  # Original production bot
  remnawave-bot:
    build: .
    container_name: remnawave-admin-bot-prod
    command: python main.py
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - REMNAWAVE_API_TOKEN=${REMNAWAVE_API_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
    env_file:
      - .env
    restart: unless-stopped
    profiles:
      - production
