services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remna-telegram-bot-test
    environment:
      - REMNA_API_URL=http://remnawave:3003/api
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    env_file:
      - .env
    networks:
      - remnawave-network
    depends_on:
      - remnawave
    restart: "no"
    # Команда для диагностики - раскомментируйте для тестирования
    command: python comprehensive_test.py
    volumes:
      - ./logs:/app/logs
      - ./diagnose_network.py:/app/diagnose_network.py
      - ./simple_tcp_test.py:/app/simple_tcp_test.py
      - ./comprehensive_test.py:/app/comprehensive_test.py
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  remnawave-network:
    external: true
