version: '3.8'

services:  remnawave-bot:
    build: .
    container_name: remna-telegram-bot-prod
    command: ["python3", "main.py"]
    environment:
      - API_BASE_URL=http://remnawave:3000/api
      - REMNAWAVE_API_TOKEN=${REMNAWAVE_API_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
      - LOG_LEVEL=INFO
    restart: unless-stopped
    depends_on:
      - remnawave
    networks:
      - remnawave-network

  # Здесь должен быть сервис remnawave, но для теста мы его не включаем
  # remnawave:
  #   image: remnawave/remnawave:latest
  #   ...

networks:
  remnawave-network:
    external: true
