version: '3.8'

services:
  remna-telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remna-telegram-bot-prod
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - REMNAWAVE_API_TOKEN=${REMNAWAVE_API_TOKEN}
      - API_BASE_URL=${API_BASE_URL:-https://remna.st/api}
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      # Optional: Persist logs
      - ./logs:/app/logs
    networks:
      - remna-bot-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getMe')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.remna.service=telegram-bot"
      - "com.remna.environment=production"

networks:
  remna-bot-network:
    driver: bridge
    name: remna-bot-network

volumes:
  logs:
    driver: local
